BEARER_PORTION = "Bearer "
ACTIVE_PROPERTY = "active"
SCOPE_PROPERTY = "scope"
SCOPES_SEPARATOR = " "
API_KEYS_SEPARATOR = ','
IP_ADDRESSES_SEPARATOR = ','
EMPTY_VALUE = ""

DEVICE_TOKEN_GRANT_TYPE = 'urn:ietf:params:oauth:grant-type:device_code'
REFRESH_TOKEN_GRANT_TYPE = 'refresh_token'

# API Metadata
API_TITLE = 'QMS IAM API'
API_SUMMARY = 'QMS Identity and Access Management API'
API_DESCRIPTION = 'QMS Identity and Access Management API.'
API_VERSION =  '1.0.0'

# API routes prefixes
AUTH_ROUTE_PREFIX = '/api/v1/auth'

# Environment names
AUTH_API_BASE_URL_ENV_NAME = "AUTH_API_BASE_URL"
AUTH_ALLOWED_IP_ADDRESSES_ENV_NAME = "AUTH_ALLOWED_IP_ADDRESSES"
AUTH_ALLOWED_API_KEYS_ENV_NAME = "AUTH_ALLOWED_API_KEYS"

# Errors
INTERNAL_SERVER_ERROR_MESSAGE = "Internal Server Error"
INTERNAL_SERVER_ERROR_CODE = 500

INVALID_TOKEN_ERROR_MESSAGE = "Invalid token"
INVALID_TOKEN_ERROR_CODE = 401

FORBIDDEN_ERROR_MESSAGE = "Forbidden"
FORBIDDEN_ERROR_CODE = 403

UNAUTHORIZED_ERROR_MESSAGE = "Unauthorized"
UNAUTHORIZED_ERROR_CODE = 401
