"""General constants
"""

BEARER_PORTION = "Bearer "
ACTIVE_PROPERTY = "active"
SCOPE_PROPERTY = "scope"
SCOPES_SEPARATOR = " "
API_KEYS_SEPARATOR = ","
IP_ADDRESSES_SEPARATOR = ","
EMPTY_VALUE = ""
TIMEOUT = 10

DEVICE_TOKEN_GRANT_TYPE = "urn:ietf:params:oauth:grant-type:device_code"
REFRESH_TOKEN_GRANT_TYPE = "refresh_token"

FORM_URL_ENCODED = "application/x-www-form-urlencoded"

# API Metadata
API_TITLE = "QMS IAM API"
API_SUMMARY = "QMS Identity and Access Management API"
API_DESCRIPTION = "QMS Identity and Access Management API."
API_VERSION = "1.0.0"

# API routes prefixes
AUTH_ROUTE_PREFIX = "/api/v1/auth"

# Environment names
AUTH_API_BASE_URL_ENV_NAME = "AUTH_API_BASE_URL"
AUTH_ALLOWED_IP_ADDRESSES_ENV_NAME = "AUTH_ALLOWED_IP_ADDRESSES"
AUTH_ALLOWED_API_KEYS_ENV_NAME = "AUTH_ALLOWED_API_KEYS"
TEST_AUTH_API_KEY_ENV_NAME = "TEST_AUTH_API_KEY"
TEST_AUTH_API_CLIENT_ID_ENV_NAME = "TEST_AUTH_API_CLIENT_ID"
TEST_AUTH_API_CLIENT_SECRET_ENV_NAME = "TEST_AUTH_API_CLIENT_SECRET"
TEST_AUTH_APPLICATION_ENV_NAME = "TEST_AUTH_APPLICATION"
TEST_AUTH_USERNAME_ENV_NAME = "TEST_AUTH_USERNAME"
TEST_AUTH_PASSWORD_ENV_NAME = "TEST_AUTH_PASSWORD"

# Errors
INTERNAL_SERVER_ERROR_MESSAGE = "Internal Server Error"
INTERNAL_SERVER_ERROR_CODE = "INTERNAL_SERVER_ERROR"

INVALID_TOKEN_ERROR_MESSAGE = "Invalid token"
INVALID_TOKEN_ERROR_CODE = "INVALID_TOKEN"

FORBIDDEN_ERROR_MESSAGE = "Forbidden"
FORBIDDEN_ERROR_CODE = "FORBIDDEN_ACCESS"

UNAUTHORIZED_ERROR_MESSAGE = "Unauthorized"
UNAUTHORIZED_ERROR_CODE = "UNAUTHORIZED"

BAD_REQUEST_ERROR_CODE = "BAD_REQUEST"

INTERNAL_ERROR_TYPE = "INTERNAL_ERROR"
AUTHORIZATION_ERROR_TYPE = "AUTHORIZATION_ERROR"
VALIDATION_ERROR_TYPE = "VALIDATION_ERROR"

# API statuses description
HTTP_400_DESCRIPTION = "Client is sending an incorrect format of API request"
HTTP_401_DESCRIPTION = "Client is not authenticated against the API"
HTTP_403_DESCRIPTION = "Client doesn't have permission to request this resource"
HTTP_404_DESCRIPTION = "Resource could not be found"
HTTP_422_DESCRIPTION = (
    "The server was unable to process the request because it contains invalid data"
)
HTTP_500_DESCRIPTION = "Unexpected internal error"
